### ISSUE TITLE
Setup the protection rules

### ISSUE THREAD

**Issue by ciiyaa** [MIT-Emerging-Talent/ET6-foundations-group-23#9]
- Require a code review for PRs.
- Require approvals
- Dismiss stale pull request approvals when new commits are pushed
- Require approval of the most recent reviewable push
- Require conversation resolution before merging
- Do not allow bypassing the above settings

**Comment by WuorBhang** [comment]
I have already added the protection rule to our repository. Don't worry about it anymore; you can refresh your browser, and you'll see that the notification is not showing anymore.

**Comment by ciiyaa** [comment]
Dear @WuorBhang I have double checked the rules, yet I can't find any applied rules. 

![Image](https://github.com/user-attachments/assets/e0a45706-ab51-4c9f-8a6d-db7f3efa9b7c)

**Comment by WuorBhang** [comment]
If you click on branch and rules under the branch, then rulesets, you will see that I have created two rules


![Screenshot (34)](https://github.com/user-attachments/assets/8747b949-1b8b-4cc5-a804-77f5def8fee7)

**Comment by ciiyaa** [comment]
We will talk about this in our next meeting.
